function generateTtsCard(
	id: number,
	name: string,
	frontUrl: string,
	backUrl: string
) {
	return {
		data: {
			Name: "Card",
			Transform: {
				posX: 0.0,
				posY: 0.0,
				posZ: 0.0,
				rotX: 0.0,
				rotY: 180.0,
				rotZ: 180.0,
				scaleX: 1.0,
				scaleY: 1.0,
				scaleZ: 1.0,
			},
			Nickname: name,
			Description: "",
			GMNotes: "",
			Locked: false,
			Grid: true,
			Snap: true,
			IgnoreFoW: false,
			MeasureMovement: false,
			DragSelectable: true,
			Autoraise: true,
			Sticky: true,
			Tooltip: true,
			GridProjection: false,
			CardID: id * 100,
			LuaScript: "",
			LuaScriptState: "",
			XmlUI: "",
		},
		model: {
			FaceURL: frontUrl,
			BackURL: backUrl,
			NumWidth: 1,
			NumHeight: 1,
			BackIsHidden: true,
			UniqueBack: false,
			Type: 0,
		},
	};
}

function generateTtsDoubleCard(
	id: number,
	name: string,
	description: string,
	firstFrontUrl: string,
	secondFrontUrl: string,
	backUrl: string
) {
	return {
		data: {
			Name: "Card",
			Transform: {
				posX: 0.0,
				posY: 0.0,
				posZ: 0.0,
				rotX: 0.0,
				rotY: 180.0,
				rotZ: 180.0,
				scaleX: 1.0,
				scaleY: 1.0,
				scaleZ: 1.0,
			},
			Nickname: name,
			Description: description,
			GMNotes: "",
			Locked: false,
			Grid: true,
			Snap: true,
			IgnoreFoW: false,
			MeasureMovement: false,
			DragSelectable: true,
			Autoraise: true,
			Sticky: true,
			Tooltip: true,
			GridProjection: false,
			CardID: id * 100,
			LuaScript: "",
			LuaScriptState: "",
			XmlUI: "",
			States: {
				2: {
					GUID: "81082a",
					Name: "Card",
					Transform: {
						posX: 0.0,
						posY: 0.0,
						posZ: 0.0,
						rotX: 0.0,
						rotY: 180.0,
						rotZ: 180.0,
						scaleX: 1.0,
						scaleY: 1.0,
						scaleZ: 1.0,
					},
					Nickname: name,
					Description: description,
					Memo: "ea9c459a-6047-43aa-968f-a582be4000e8",
					Value: 0,
					Locked: false,
					Grid: true,
					Snap: true,
					IgnoreFoW: false,
					MeasureMovement: false,
					DragSelectable: true,
					Autoraise: true,
					Sticky: true,
					Tooltip: true,
					GridProjection: false,
					HideWhenFaceDown: true,
					Hands: true,
					CardID: id * 100,
					SidewaysCard: false,
					CustomDeck: {
						[id]: {
							FaceURL: secondFrontUrl,
							BackURL: backUrl,
							NumWidth: 1,
							NumHeight: 1,
							BackIsHidden: true,
							UniqueBack: false,
							Type: 0,
						},
					},
				},
			},
		},
		model: {
			FaceURL: firstFrontUrl,
			BackURL: backUrl,
			NumWidth: 1,
			NumHeight: 1,
			BackIsHidden: true,
			UniqueBack: false,
			Type: 0,
		},
	};
}

function generateTtsDeckObject() {
	return {
		Name: "DeckCustom",
		Transform: {
			posX: 36.25,
			posY: 5.11282444,
			posZ: 6.645,
			rotX: 0.0130744949,
			rotY: 0.03566377,
			rotZ: 180.000275,
			scaleX: 1.0,
			scaleY: 1.0,
			scaleZ: 1.0,
		},
		Nickname: "",
		Description: "",
		GMNotes: "",
		ColorDiffuse: {
			r: 0.713235259,
			g: 0.713235259,
			b: 0.713235259,
		},
		Locked: false,
		Grid: true,
		Snap: true,
		IgnoreFoW: false,
		MeasureMovement: false,
		DragSelectable: true,
		Autoraise: true,
		Sticky: true,
		Tooltip: true,
		GridProjection: false,
		HideWhenFaceDown: true,
		Hands: false,
		SidewaysCard: false,
		DeckIDs: [0],
		CustomDeck: {},
		LuaScript: "",
		LuaScriptState: "",
		XmlUI: "",
		ContainedObjects: [{}],
	};
}

function generateTtsDeckBox() {
	return {
		SaveName: "",
		GameMode: "",
		Date: "",
		Gravity: 0.5,
		PlayArea: 0.5,
		GameType: "",
		GameComplexity: "",
		Tags: [],
		Table: "",
		Sky: "",
		Note: "",
		Rules: "",
		TabStates: {},
		ObjectStates: [
			{
				Name: "Custom_Model_Bag",
				Transform: {
					posX: 35.4643936,
					posY: 2.8808763,
					posZ: 5.782154,
					rotX: -2.01687612e-6,
					rotY: -0.00141442078,
					rotZ: 8.571432e-7,
					scaleX: 1.0,
					scaleY: 1.0,
					scaleZ: 1.0,
				},
				Nickname: "Card Deck",
				Description: "",
				GMNotes: "",
				ColorDiffuse: {
					r: 0.9999998,
					g: 0.992163241,
					b: 0.9999998,
				},
				Locked: false,
				Grid: false,
				Snap: true,
				IgnoreFoW: false,
				MeasureMovement: false,
				DragSelectable: true,
				Autoraise: true,
				Sticky: true,
				Tooltip: true,
				GridProjection: false,
				HideWhenFaceDown: false,
				Hands: false,
				MaterialIndex: -1,
				MeshIndex: -1,
				CustomMesh: {
					MeshURL: "https://www.dropbox.com/s/fbpp2c2mzvdi2lg/DeckBox.obj?dl=1",
					DiffuseURL:
						"https://www.dropbox.com/s/o53xastt2846bmt/DeckBox.jpg?dl=1",
					NormalURL: "",
					ColliderURL: "",
					Convex: true,
					MaterialIndex: 2,
					TypeIndex: 6,
					CastShadows: true,
				},
				LuaScript: "",
				LuaScriptState: "",
				XmlUI: "",
				ContainedObjects: [{}],
			},
		],
		LuaScript: "",
		LuaScriptState: "",
		XmlUI: "",
		VersionNumber: "",
	};
}

function generateTtsSingleCard(
	id: number,
	name: string,
	frontUrl: string,
	backUrl: string
) {
	return {
		Name: "Card",
		Transform: {
			posX: -33.75,
			posY: 4.633549,
			posZ: -9.805,
			rotX: 359.840668,
			rotY: -0.0008630832,
			rotZ: 359.920532,
			scaleX: 1.0,
			scaleY: 1.0,
			scaleZ: 1.0,
		},
		Nickname: name,
		Description: "",
		GMNotes: "",
		ColorDiffuse: {
			r: 0.713235259,
			g: 0.713235259,
			b: 0.713235259,
		},
		Locked: false,
		Grid: true,
		Snap: true,
		IgnoreFoW: false,
		MeasureMovement: false,
		DragSelectable: true,
		Autoraise: true,
		Sticky: true,
		Tooltip: true,
		GridProjection: false,
		HideWhenFaceDown: true,
		Hands: true,
		CardID: id * 100,
		SidewaysCard: false,
		CustomDeck: {
			[id]: {
				FaceURL: frontUrl,
				BackURL: backUrl,
				NumWidth: 1,
				NumHeight: 1,
				BackIsHidden: true,
				UniqueBack: false,
				Type: 0,
			},
		},
		LuaScript: "",
		LuaScriptState: "",
		XmlUI: "",
	};
}

export {
	generateTtsCard,
	generateTtsDoubleCard,
	generateTtsDeckObject,
	generateTtsDeckBox,
	generateTtsSingleCard,
};
